### PR TITLE
Backport to iOS 14

### PR DESCRIPTION
**Pull request by ilyamodder**
I think hacker device's companion app should be compatible with hacked iPhones. Since there's no jailbreak for iOS 15 or newer, we need a backport :)

Changed deployment target to 14.0, made required edits. ~~Didn't really tested it, because I'm still waiting for my Flipper to arrive (that's why this PR is a draft)~~ UPD: tested, fixed.

### CODE REVIEW

**Comment by tokfrans03** [comment]
Awesome work! 
Just got mine and discovered that the app requires iOS 15 (I have 14.3), and the latest version that supports iOS 14 is 1.0.0.

Thank you open source!

**Comment by danpalmer** [comment]
Bumping this because it's been open a long time and we don't want it to bit-rot 😄 . @tonyfreeman (picking you as biggest contributor).

I can understand why the Flipper team might not want to support iOS 14, but also I think "last jailbroken release" is a reasonable compatibility target as @ilyamodder suggested.

Can we get a final say one way or the other? If _no_, that sounds fine, maybe a note in the readme about the compatibility goal would be a nice clarification. If _yes_, great! I've reviewed this PR, got a fair bit of Swift(+UI) experience and this all seems reasonable to me, seems ready for a final review with a view to merging.

**Comment by pikkio92** [comment]
this is marked as solved but i cannot figure out how to download the ios 14 compatibile .ipa

**Comment by tonyfreeman** [comment]
Is this still relevant? AFAIK there is jb for iOS15-iOS16.

**Comment by tokfrans03** [comment]
> Is this still relevant? AFAIK there is jb for iOS15-iOS16. 

There is, but because of the nature of jailbreaks there are still some who still have devices on iOS 14 since you usually have to wait months on a specific version before there is a jailbreak publicly available for that version.

**Comment by ibboccan** [comment]
> I think hacker device's companion app should be compatible with hacked iPhones. Since there's no jailbreak for iOS 15 or newer, we need a backport :)
> 
> 
> 
> Changed deployment target to 14.0, made required edits. ~~Didn't really tested it, because I'm still waiting for my Flipper to arrive (that's why this PR is a draft)~~ UPD: tested, fixed.
> 
>

**Pull request closed without merging**
