### PR TITLE
Implemented Siri shortcut to send/emulate archived items via Flipper.

### PR DESCRIPTION
**Pull request by MarcoPieroni**
I've recently joined the Flipper Zero user family and I'm a very happy user.
I noticed that the app doesn't support Siri Shortcuts, so I've decide to implement a simple shortcut that allows the user to pick one of the archived items from the app and send it via the Flipper.

If the `item.kind` is `.subghz` or `.infrared` the Flipper will send the `item` for the `item.duration` time and then stop.
If the `item.kind` is of type `.nfc`, `.rfid` or `.ibutton` the Flipper will enter in emulation mode and will require manual interaction to stop.

I've implemented also error handling for both the "not connected" and "busy" cases so that the user has a clear understanding of what's going on during usage.

If you have an Apple watch associated with your iPhone and set the shortcut to "Show on Apple Watch" inside the Shortcuts app, it works perfectly also when recalled from the watch (I've tested this use case extensively because it's the main reason I implemented this whole thing). The reaction time is almost immediate and error handling works the same.

The small change I've made to the Dependencies object is to get rid of some `Reference to class property 'shared' is not concurrency-safe because it involves shared mutable state` warnings that I had while accessing the dependencies from my code. I've tested the app and I don't see any issue with this change and seems safe to merge, but my knowledge of your codebase is of course not enough to be 100% certain. This change is not really needed for the shortcuts code to work, and the dependencies are used only for reading the items and sending them through Flipper, not altering them.

Regarding copy writing I tried to be as clear as possible, but is understandable if you want to change the messages according to your UX guidelines.

Below some screenshots:

| Shortcuts screen  |  Parameter selection  | Siri confirmation | Error handling | 
| -----------------  | ----------------  | ---------------- | ---------------- |
|IMG_3976 IMG_3977|IMG_3979IMG_3980|IMG_3981IMG_3983|IMG_3984IMG_3985|

### CODE REVIEW

**Comment by tonyfreeman** [comment]
Great work! Thank you!

**Comment by MarcoPieroni** [comment]
> Great work! Thank you!

Welcome, happy to help!
Keep up the great work with this app, is very well structured 💪🏼

**Comment by hmvs** [comment]
Hey @MarcoPieroni.
Thanks for the great feature. 

Do you know how to send a specific infrared command if a file (item) has multiple commands?

**Comment by The-Johnson** [comment]
This feature looks awesome, though I cannot figure out how to send an infrared command using it.

What I initially set out to do was to have the shortcut send a playlist of infrared commands I had saved with the CrossRemote flipper app. I figured this won't work, so I tried simplifying and thought I could re-build the playlist in the shortcuts app itself.

I tried sending any of the saved ir remotes I already had, but no result. 
I figured it must be because they have multiple commands saved in them, so I saved a remote with just one ir command inside, still no result when sending it via shortcut.

Am I missing something, is there some way to create a single command infrared item and send that, all I see is ways to save remotes in the flipper.

**Pull request merged**
